theme: jekyll-theme-minimal
layout: default
logo: logo.png
title: 'WSCC: Chess club in Port Orchard in Kitsap County, WA'
tagline: 'Chess club in Port Orchard, WA'
url: https://chessand.beer
description: 'Chess club based out of Port Orchard and Bremerton, WA in Kitsap County. All skill levels welcome!'
